[workspace]
members = [
    "everymap-core",
    "everymap-providers-here",
    "everymap-providers-google",
    "everymap-cli",
    "everymap-providers-tomtom",
    "everymap-providers-mapbox",
    "everymap-providers-radar",
    "everymap-bench",
]
resolver = "2"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"
reqwest = { version = "0.12", features = ["json"] }
thiserror = "1.0"
futures = "0.3"
flexpolyline = "1.0"
wiremock = "0.6"